version: "3.9"
   
services:
  web:
    build: .
    environment:
      - BASE_URL=http://127.0.0.1:5000
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"